spring:
  application:
    name: Taiken Sushi
  datasource:
    url: jdbc:postgresql://localhost:5432/taiken
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/taiken